openapi: 3.0.1
info:
  title: Документация API между клиентом и беком для Go Explore
  version: 0.0.1
servers:
  - url: https://<backend url>/api/v1
tags:
  - name: places
    description: API для работы с местами
paths:
  /place:
    get:
      tags:
        - places
      summary: "Информация по местам"
      responses:
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/Internal'
components:
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          examples:
            BAD/REQUEST:
              value:
                error: NOT/FOUND
    Internal:
      description: Internal server error
      content:
        application/json:
          example:
            error: INTERNAL